### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by p0358**
* Preferences are read once in constructor (ctor), then dynamically updated via notifications, no depedencies needed!
  * that should improve the performance by not reading the preferences file every time battery is discharged
  * removed respring button as it's not needed anymore, all changes are applied instantly
  * changes appliance resets the alert shown boolean
* I've cleaned up the code, original function is now called only once and its result returned
* `HBLogDebug` will only be compiled into debug builds for testing, make sure to compile public release versions with `FINALPACKAGE=1 make package`
* I removed Theos device IP and port as these are specific to the environment and not the package, these should go to .profile next and analogous to `export THEOS=...` directive
* Renamed tweak name from fivepercentalert to FivePercentAlert as that looks better
* Added preference subproject to Makefile, no idea why it wasn't there before, but if it was like that in release version, then users didn't have the preferences bundle on their devices

You can credit me somewhere sometime if you want xd

### CODE REVIEW

**Comment by ahoynodnarb** [comment]
you declared a static bool isEnabled but isEnabled is determined by the preferencefile so there's no need to declare in tweak.xm

**Comment by p0358** [comment]
Yes, but that static bool is a global in Tweak.xm. `reloadPrefs()` function pulls in the value from preference file and puts that into this global. Later `_shouldIgnoreChangeToBatteryLevel` only checks this bool instead of loading and reading preference file every single time battery level is changed. And dynamic preference refreshes are working and are handled by notification listener, which calls `reloadPrefs()` only after the preferences were actually changed by the user

**Comment by ahoynodnarb** [comment]
Okay that makes sense I didn't look too much into detail. I also noticed you're missing alot of curly braces for your if statements was that a typo?

**Comment by ahoynodnarb** [comment]
I also noticed in some of the if statements they can be made less confusing by using YES or NO instead of the value of a different specific bool

**Comment by p0358** [comment]
> Okay that makes sense I didn't look too much into detail. I also noticed you're missing alot of curly braces for your if statements was that a typo?

Nope, if there's only one instruction after the if statement, there is no need to use curly braces. It might be a matter of preference, but I do believe that it can make the code much more readable in certain situations.

> I also noticed in some of the if statements they can be made less confusing by using YES or NO instead of the value of a different specific bool

I assume you're talking about `wasEnabled` variable?

**Comment by ahoynodnarb** [comment]
Yes but other than a few things to make it easier to read I think this code is perfect and I'm ready to test it out

**Review by ahoynodnarb — APPROVED** [review]
Change `if (!wasEnabled) [myDevice setBatteryMonitoringEnabled:wasEnabled];` to `if (!wasEnabled) [myDevice setBatteryMonitoringEnabled:YES];` so that it's easier to read

**Comment by p0358** [comment]
But it's supposed to be NO there :D 
The purpose is to restore the original value if it was NO in the first place (`wasEnabled` stores what it was before we changed it to YES)

And it's only set to YES if it wasn't YES already (thus the `if (!wasEnabled)` check(s))

**Comment by ahoynodnarb** [comment]
Yeah I meant no I'm tired but just change that and I'll merge it

**Comment by ahoynodnarb** [comment]
I got like 2 hours of sleep lmao

**Comment by p0358** [comment]
I can feel you, I know what's my level of thinking after I sleep 2 hours myself

**Comment by p0358** [comment]
And in general I tested that alerts for discharge works and that dynamically updating the settings works, I didn't have a chance to test recharging, but I don't see a reason it wouldn't work

**Comment by p0358** [comment]
Hope it helps :)

**Pull request merged**
